= ogurets for Jetbrains IDEs

This plugin brings full support for Ogurets to IntelliJ IDEA - piggybacking on Jetbrains existing Cucumber plugins.
It should work in any variant that has Cucumber (including Android Studio) and at least Dart installed,
and if it detects Flutter, it will also support Flutter FlutterDriver tests.

== features

- Full support for creating and navigating to cucumber steps inside classes
- Creation of classes that hold the steps
- Full run and _debug_ support for Features, Feature folders and Scenarios
- Full stack trace following for failures
- Automatic run configuration generation for your IDEA Ogurets Run Configurations
- Recognition of Given/When/Then annotations as regexes as such so they are treated properly by IDEA
- Full integration with the Test panel, with Jump to Source for IntelliJ

== authors

- _Irina Southwell (nee Капрельянц Ирина)_, Principal Engineer (https://www.linkedin.com/in/irina-southwell-9727a422/)
- _Richard Vowles_, Software Developer (https://www.linkedin.com/in/richard-vowles-72035193/)

