= Setup

IDEA plugins are a _pain_ to set up, each release of this if I haven't set it up takes me two
days or so of work to figure out how to set it up again. So these are my notes:

Your deps need to look like this to be able to run and debug it. It needs to run as a Plugin project. At the top
of the iml file there is:

----
<?xml version="1.0" encoding="UTF-8"?>
<module type="PLUGIN_MODULE" version="4">
----

That indicates this

You can create a Plugin run config once this happens, make sure its  the latest version of 11 otherwise it bombs (11.0.11)

You are going to need IDEA configured as a plugin dep and the library of the installed IDEA as well as you need the
gherkin.jar and dart.jar plugin files from it.

ensure you get the intellij-plugins github repo, and then swap to your version of intellij. My tag as of writing is

`git checkout idea/191.7479.19`

this ensures your code is written against the write version of the libs.

You need to add cucumber (gherkin) to your project and then add those modules as dependencies to cucumber-dart. You cannot
add Dart as it's dependencies make it unusable.

get your plugins directory so you can get Dart

ln -s /Users/<your-name>/Library/Application\ Support/IntelliJIdea2019.1 ~/projects/dart/cucumber-dart/plugins

You need to install

and run the maven build in the repo so it downloads the dependencies

mvn dependency:tree

and then:

ln -s ~/.m2/repository/io/cucumber ~/projects/dart/cucumber-dart/cucumber-io

and add the jars referred to in the pom.

Make sure all of these dependencies are _provided_. Thats important if they are included in the plugin when
you run it in the IDE all hell breaks loose because they are already core to even the community edition, so you
end up with two of them and nothing works. Especially run configurations.

==== using latest IDEA

`ln -s "/Applications/IntelliJ IDEA.app/Contents/plugins" current-idea-plugins`